# fly.toml app configuration file generated for our-bot on 2025-09-05T22:12:52+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'our-bot'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
